### PR TITLE
Update project with webpack and support for SASS

### PR DESCRIPTION
**Pull request by Kalikoze**
**Description of changes made**
- Add webpack to project and support for SASS/SCSS.
- As a result, also needed to add a webpack config file and a `.gitignore` file.
- `index.html` has been moved to `dist` directory.  `index.js` and scss/images have been moved to a `src directory.

**Motivation for any changes**
- The hope with this is to motivate students to get more out of the SCSS lesson and have an opportunity to practice this more in the static comp.  Perhaps there may be more motivation to include it in the final project as well.

**Questions that you have for a reviewer**
- When you install the application and run `npm start`, does the app open correctly?  
- Try adding some HTML, SCSS, incorporating the variables partial, etc. and double check everything works correctly.
- Currently the background image loads, but the image in the HTML does not load.  Any idea what needs to be updated in the file path or in the `webpack.config.js` file?

### CODE REVIEW

**Comment by kaylagordon** [comment]
When you install the application and run npm start, does the app open correctly?
- YES

Try adding some HTML, SCSS, incorporating the variables partial, etc. and double check everything works correctly.
- ✅
- I do think it might be good to provide an example for them. I've pushed up a commit with that, but we can remove it if you don't think we should include it!

Currently the background image loads, but the image in the HTML does not load. Any idea what needs to be updated in the file path or in the webpack.config.js file?
- `work in progress`

**Comment by kaylagordon** [comment]
Okay, so I got the images working by following this tutorial: https://requestmetrics.com/web-performance/optimizing-static-html-images-webpack/

I had to add the html loader and plugin, and move all the images to within the `dist` folder. This did not seem to affect being able to use images in CSS, as the backgroun image is working fine.

To test, please install and run `npm start` and make sure the background image and dog icon are appearing as expected.

**Comment by Kalikoze** [comment]
Hmmm I have tested it but ran into a few issues.  

1. There is a missing import for `html-webpack-plugin` inside of the `webpack.config.js` file.
2. After adding it in, I also noticed that the `html-loader` was missing from the `package.json` file.
3. Lastly, when I tested it out, the image loaded correctly but now the CSS/SCSS file is not being loaded.  Upon further investigation, it seems like the `index.js` file is being ignored (no console.logs will show), where the import of the SCSS file happens.

Perhaps we can hop on a call to compare later today?

**Comment by kaylagordon** [comment]
I just removed the HTML plugin (It doesn't seem like it was necessary).

CSS is working on my end.

JS is working on my end (I am able to console log)

I added the html-loader to package.json - good catch! 

Everything seems to be working, but it was also working for me earlier so you'll definitely want to test it!

**Pull request merged**
